Feature/comment
prography/five-minutes-backend pull request #27
Opened 2019-05-18 07:42 UTC by kang-heewon

2019-05-18 07:42 UTC, kang-heewon commented
조오금 부족한 감이 있는데 때려주세요

2019-05-19 12:26 UTC, geusan requested changes

2019-05-19 12:26 UTC, geusan commented on src/Dto/CommentCreateDto.ts
> +  type!: string;
type과 status는 ENUM 으로 해줘!

2019-05-19 12:26 UTC, geusan commented on src/models/Comment.ts
> +  type!: string;
여기두 ENUM 으로 맞추자

2019-05-19 12:26 UTC, geusan commented on src/services/CommentService.ts
> +  async update(id: number, commentForm: CommentUpdateDto): Promise<Comment> {
update는 댓글 내용과 type만 수정하고
changeStatus라고 만들어서 상태만 수정하는 기능을 만들어줘

2019-05-19 12:26 UTC, geusan commented on src/controllers/CommentController.ts
>    updateComment(@Param('id') id: number, @Body() comment: Comment) {
Comment 가 아니라 CommentUpdateDto 가 아닌가?

2019-05-20 04:56 UTC, kang-heewon commented on src/controllers/CommentController.ts
>    updateComment(@Param('id') id: number, @Body() comment: Comment) {
예아스

2019-05-20 04:56 UTC, kang-heewon commented on src/services/CommentService.ts
> +  async update(id: number, commentForm: CommentUpdateDto): Promise<Comment> {
으흠 그럼 기본은 빈값넣을게

2019-05-20 04:56 UTC, kang-heewon commented on src/models/Comment.ts
> +  type!: string;
오키도키

2019-05-20 04:56 UTC, kang-heewon commented on src/Dto/CommentCreateDto.ts
> +  type!: string;
오키

2019-05-20 05:07 UTC, geusan commented on src/services/CommentService.ts
> +  async update(id: number, commentForm: CommentUpdateDto): Promise<Comment> {
PENDING / RESOLVE / REJECT / WAIT 해서 이것저것 상태를 넣으려고 했었으

WAIT : default, 작성자가 확인하는 것을 기다리는 상태
PENDING: 작성자가 확인하고 변경 중임
RESOLVE: 작성자가 확인하고 변경도 완료(현재는 작성자가 확인하면 바로 RESOLVE)
REJECT: 작성자가 해당 요청을 거부

기본 값은 WAIT 상태로

2019-05-20 05:08 UTC, kang-heewon commented on src/services/CommentService.ts
> +  async update(id: number, commentForm: CommentUpdateDto): Promise<Comment> {
아하 오키오키

2019-05-21 01:26 UTC, geusan commented
enum 만드는거 확인해줘

2019-05-21 14:36 UTC, geusan approved these changes

2019-05-21 14:36 UTC, merged